name: deploy-docusaurus

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          npm install 
          npm run build
          
      # Install and build Docusaurus website        
      - name: Deploy Docusaurus website
        run: |
          git config --global user.name "16jalayt"
          git config --global user.email "16jalayt@gmail.com"
          GIT_USER=16jalayt USE_SSH=true npm run deploy
