name: deploy-docusaurus

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          npm install 
          npm run build
          
      # Install and build Docusaurus website
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          name: '16jalayt'
          token: '${{ secrets.GITHUB_TOKEN }}'
          
      - name: Deploy Docusaurus website
        run: |
          npm run deploy
